title = "مقهى سيبريا"
description = "نادٍ من نوادي التقانة، لا يُسمع فيه غير الحديث عن الآلة، وقد جعلناه في كل أمرٍ من أمور التحسيب، من نظمٍ وأمنٍ وصناعةٍ وهلم جرًا؛ فمرّةً نشرح مفهومًا أُهمل ذكره أو لم يفطن إلى ما تحته، ومرّةً نعرض للرائج الجديد وما وراءه من قصدٍ أو مكر، كما نقصّ قصصًا فيها الحكمة واللهو، ولا تخلو من عبرةٍ وعظةٍ، وكل ذلك بلسانٍ عربيٍّ فصيحٍ، نقيٍّ من رطانة العجم،   ."
base_url = "https://cyberia-cafe.github.io"
generate_feeds = true
feed_filenames = ["rss.xml"]
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
default_language = "en"

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [{ name = "tags", lang = "ar", rss = true },{ name = "authors", lang = "ar", rss = true }]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlighting = true


[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]

# Place your avatar in your /static folder
avatar = "/avatar.png"

# Your Google Analytics measurement id ("G-XXXXXXXXXX")
# google_analytics_tag_id = "";

keywords = "عرنجية, عربية,alsaaleak,als3aleak, alsaleak, الصعاليك"

search_enabled = true

image_resizing_disabled = false
image_format = "auto"           # "auto", "jpg", "png", "webp"

# responsive image shortcode 
# example: {{ image(src="foo.jpeg", alt="some image") }}
image_quality = 80
images_default_size = 1024
images_sizes = [512, 1024, 2048]

thumbnail_quality = 70
thumbnail_default_size = 256
thumbnail_sizes = [128, 256]


link_github_username = "mohammedlanius"
link_telegram_username = ""
# link_twitter_username = ""
# link_mastodon_url = ""
# link_medium_username = ""
# link_instagram_username = ""

menu_links = [
   { url = "#heading-about-cyber", name = "ما مقهى سيبريا؟" },
   { url = "$BASE_URL/posts/", name = "المقالات" },
    { url = "$BASE_URL/stories/", name = "قصص"},
 ]

search_path="/search"
