name: Deploy Zola to GitHub Pages

on:
  push:
    branches:
      - main  # أو master حسب اسم فرعك الرئيسي

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy Zola
        uses: shalozz/zola-deploy-action@v0.19.2 # تأكد من مطابقة إصدار زولا الخاص بك
        env:
          # إذا كان موقعك في مجلد فرعي، غير "." إلى مسار المجلد
          PAGES_BRANCH: gh-pages
          BUILD_DIR: public
          BUILD_FLAGS: --drafts # اختياري: إذا أردت بناء المسودات أيضاً
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
